"""Core Pydantic schemas for FixerAgent."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class RepairTier(int, Enum):
    """Repair complexity / safety tier."""
    DIY_EASY = 1
    DIY_MODERATE = 2
    DIY_ADVANCED = 3
    PROFESSIONAL_ONLY = 4


class FaultType(str, Enum):
    """Standardized fault taxonomy."""
    PAPER_JAM = "paper_jam"
    CONNECTIVITY_ERROR = "connectivity_error"
    HARDWARE_FAILURE = "hardware_failure"
    FIRMWARE_ERROR = "firmware_error"
    POWER_SUPPLY_ISSUE = "power_supply_issue"
    FILTER_CLOG = "filter_clog"
    SEAL_FAILURE = "seal_failure"
    MECHANICAL_WEAR = "mechanical_wear"
    USER_ERROR = "user_error"
    UNKNOWN = "unknown"


class OutcomeStatus(str, Enum):
    """User-reported repair outcome."""
    FIXED = "fixed"
    PARTIAL = "partial"
    FAILED = "failed"


class KnowledgeStatus(str, Enum):
    """Knowledge atom provenance status."""
    VERIFIED = "VERIFIED"
    RESEARCH = "RESEARCH"
    COMMUNITY = "COMMUNITY"
    INFERRED = "INFERRED"


class LLMProvider(str, Enum):
    """Supported external LLM providers."""
    CLAUDE = "claude"
    OPENAI = "openai"
    GEMINI = "gemini"
    LOCAL = "local"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class DeviceInfo(BaseModel):
    """Identified device metadata."""
    device_category: str = Field(..., examples=["printer", "microwave", "router"])
    brand: str | None = Field(None, examples=["HP", "Samsung", "Canon"])
    model_candidates: list[str] = Field(default_factory=list)
    model_confidence: float = Field(0.0, ge=0.0, le=1.0)
    model_number_ocr: str | None = Field(None, description="Raw OCR output from device label")


class ErrorIndicators(BaseModel):
    """Visual / reported error signals."""
    led_pattern: str | None = Field(None, examples=["blinking_red_4x", "solid_amber"])
    display_code: str | None = Field(None, examples=["E03", "SE", "F-3"])
    physical_damage: list[str] = Field(default_factory=list)
    audible_symptoms: list[str] = Field(default_factory=list)
    user_description: str | None = None


class SafetyAssessment(BaseModel):
    """Safety evaluation for a repair."""
    tier: RepairTier
    tier_label: str = Field(..., examples=["DIY Easy", "DIY Moderate", "Professional Only"])
    requires_unplug: bool = True
    electrical_hazard_v: float | None = Field(None, description="Maximum voltage present")
    capacitor_risk: bool = False
    gas_or_refrigerant: bool = False
    escalation_reason: str | None = None
    warnings: list[str] = Field(default_factory=list)


class RepairStep(BaseModel):
    """Single numbered repair instruction."""
    step_number: int = Field(..., ge=1)
    title: str
    instruction: str
    image_reference: str | None = None
    tools_needed: list[str] = Field(default_factory=list)
    parts_needed: list[str] = Field(default_factory=list)
    estimated_time_min: int | None = None
    caution_notes: list[str] = Field(default_factory=list)


class LLMConfig(BaseModel):
    """User-configured external LLM provider."""
    provider: LLMProvider = LLMProvider.CLAUDE
    model: str = "claude-sonnet-4-6"
    api_key: str | None = None
    temperature: float = 0.2
    max_tokens: int = 2000
    fallback: Literal["internal", "next_provider"] = "internal"

    @field_validator("temperature")
    @classmethod
    def _clamp_temp(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


# ---------------------------------------------------------------------------
# Top-level payloads
# ---------------------------------------------------------------------------

class DiagnosticPayload(BaseModel):
    """Structured output from the Vision / Diagnosis module."""
    device_info: DeviceInfo
    error_indicators: ErrorIndicators
    visible_components: list[str] = Field(default_factory=list)
    fault_type: FaultType = FaultType.UNKNOWN
    fault_confidence: float = Field(0.0, ge=0.0, le=1.0)
    raw_vision_output: dict[str, Any] | None = None

    @property
    def proceed_with_diagnosis(self) -> bool:
        return self.device_info.model_confidence >= 0.85

    @property
    def needs_clarification(self) -> bool:
        return 0.60 <= self.device_info.model_confidence < 0.85

    @property
    def needs_better_input(self) -> bool:
        return self.device_info.model_confidence < 0.60


class RepairGuide(BaseModel):
    """User-facing repair guide generated by the agent."""
    session_id: str = Field(..., description="Unique diagnosis session identifier")
    device_name: str
    fault_description: str
    safety: SafetyAssessment
    estimated_total_time: str = Field(..., examples=["15-20 minutes"])
    tools_needed: list[str] = Field(default_factory=list)
    parts_needed: list[str] = Field(default_factory=list)
    parts_links: list[dict[str, str]] = Field(default_factory=list)
    steps: list[RepairStep]
    test_procedure: str
    troubleshooting_fallback: str
    source_attribution: str = Field(..., description="Manual name / source that grounded the guide")
    knowledge_confidence: float = Field(0.0, ge=0.0, le=1.0)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    enhanced_by_llm: str | None = Field(None, description="Tag if external LLM enhanced this guide")

    def to_markdown(self) -> str:
        """Render guide as markdown per CLAUDE.md output standard."""
        lines = [
            f"## đŸ”§ Repair Guide: {self.device_name} â€” {self.fault_description}",
            "",
            f"**Risk Level**: {self.safety.tier_label}",
            f"**Estimated Time**: {self.estimated_total_time}",
            f"**Tools Needed**: {', '.join(self.tools_needed) if self.tools_needed else 'None'}",
            f"**Parts Needed**: {', '.join(self.parts_needed) if self.parts_needed else 'None'}",
            "",
            "---",
            "",
            "â ï¸ **SAFETY FIRST**: Unplug the device before starting. "
            f"{' '.join(self.safety.warnings)}",
            "",
            "---",
            "",
        ]
        for step in self.steps:
            lines.extend([
                f"### Step {step.step_number}: {step.title}",
                step.instruction,
                "",
            ])
            if step.caution_notes:
                lines.append(f"**Caution**: {' '.join(step.caution_notes)}")
                lines.append("")
        lines.extend([
            "---",
            "",
            f"âœ… **Test**: {self.test_procedure}",
            f"đŸ“ **Still broken?** {self.troubleshooting_fallback}",
            "",
            f"*Guide sourced from: {self.source_attribution}*",
            f"*Knowledge confidence: {self.knowledge_confidence:.0%} | "
            f"Last updated: {self.generated_at.strftime('%Y-%m-%d')}*",
        ])
        if self.enhanced_by_llm:
            lines.append(f"\n*{self.enhanced_by_llm}*")
        return "\n".join(lines)


class FeedbackOutcome(BaseModel):
    """User feedback on a repair attempt."""
    session_id: str
    outcome: OutcomeStatus
    notes: str | None = None
    user_skill_level: Literal["beginner", "intermediate", "advanced"] | None = None
    actual_time_min: int | None = None
    parts_purchased: list[str] = Field(default_factory=list)
    submitted_at: datetime = Field(default_factory=datetime.utcnow)


class KnowledgeAtom(BaseModel):
    """Single curated fact in SECOND-KNOWLEDGE-BRAIN.md."""
    atom_id: str = Field(..., pattern=r"^[KR]-\d{3}$")
    title: str
    tags: list[str] = Field(default_factory=list)
    status: KnowledgeStatus
    confidence: float = Field(..., ge=0.0, le=1.0)
    source: str
    last_updated: datetime | None = None
    content: str
    implication: str | None = None


class CrawlStatus(BaseModel):
    """State of the automated knowledge crawl pipeline."""
    last_run: datetime | None = None
    next_scheduled: datetime | None = None
    documents_added: int = 0
    errors: list[str] = Field(default_factory=list)
    sources_crawled: list[str] = Field(default_factory=list)


class RetrievalChunk(BaseModel):
    """A single retrieved document chunk from RAG."""
    content: str
    metadata: dict[str, Any] = Field(default_factory=dict)
    dense_score: float = 0.0
    sparse_score: float = 0.0
    fused_score: float = 0.0
    rerank_score: float | None = None


class DiagnosisRequest(BaseModel):
    """API request body for /diagnose."""
    image_base64: str | None = None
    description: str = ""
    device_hint: str = ""
    llm_config: LLMConfig | None = None


class DiagnosisResponse(BaseModel):
    """API response body for /diagnose."""
    session_id: str
    status: Literal["success", "escalated", "needs_clarification", "needs_input", "error"]
    guide: RepairGuide | None = None
    message: str | None = None
    safety: SafetyAssessment | None = None
    diagnosis: DiagnosticPayload | None = None